# Generated by Django 4.2.10 on 2024-04-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
